[features]
seeds = false
[programs.localnet]
soltwt = "5ArNY34VRyGLvcsoM67nCc6uzAcmcMgYJ1RuUXQPdQze"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kwaybot/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
